// lista de jogos: [slug, nome, [categorias]]
var GAMES = [
["10-minutes-till-dawn","10 Minutes Till Dawn",["tiro"]],
["1v1-lol","1v1.LOL",["tiro","esportes"]],
["2048","2048",["puzzle"]],
["2MinuteFootball","2 Minute Football",["esportes"]],
["awesome-tanks-2","Awesome Tanks 2",["tiro","estrategia"]],
["basket-random","Basket Random",["esportes"]],
["basketball-stars","Basketball Stars",["esportes"]],
["bit-planes","Bit Planes",["plataforma"]],
["bitlife","BitLife",["simulacao"]],
["block-blast","Block Blast",["puzzle"]],
["bloxors","Bloxors",["puzzle","estrategia"]],
["boxing-random","Boxing Random",["esportes"]],
["BTD-1","Bloons TD 1",["estrategia"]],
["BTD-2","Bloons TD 2",["estrategia"]],
["BTD-3","Bloons TD 3",["estrategia"]],
["BTD-4","Bloons TD 4",["estrategia"]],
["BTD-5","Bloons TD 5",["estrategia"]],
["burgers-and-frights","Burgers and Frights",["cozinha","terror"]],
["Burrito-Bison","Burrito Bison",["plataforma"]],
["challenge-the-runners","Challenge the Runners",["corrida","plataforma"]],
["chrome-dino","Chrome Dino",["infinito","plataforma"]],
["clickerheros","Clicker Heroes",["clicker"]],
["cluster-truck","Cluster Truck",["corrida"]],
["cod-zombies","COD Zombies",["tiro","terror"]],
["cookie-clicker","Cookie Clicker",["clicker"]],
["craft-mine","Craft Mine",["simulacao"]],
["crazy-cat-3d","Crazy Cat 3D",["corrida"]],
["crazy-cattle-3d","Crazy Cattle 3D",["corrida"]],
["crazy-chicken-3d","Crazy Chicken 3D",["corrida"]],
["crossy-road","Crossy Road",["infinito","plataforma"]],
["deal-or-no-deal","Deal or No Deal",["estrategia"]],
["DNAtoRNAandAminoAcids","DNA para RNA",["educativo"]],
["doom","Doom",["tiro","reto"]],
["drift-boss","Drift Boss",["corrida"]],
["drift-hunters","Drift Hunters",["corrida"]],
["duck-life-1","Duck Life 1",["simulacao"]],
["duck-life-2","Duck Life 2",["simulacao"]],
["duck-life-3","Duck Life 3",["simulacao"]],
["duck-life-4","Duck Life 4",["simulacao"]],
["dune-2","Dune 2",["estrategia","reto"]],
["eggy-car","Eggy Car",["corrida"]],
["evil-glitch","Evil Glitch",["plataforma"]],
["flappy-birb","Flappy Birb",["infinito","plataforma"]],
["FNAF-1","FNAF 1",["terror"]],
["FNAF-2","FNAF 2",["terror"]],
["FNAF-3","FNAF 3",["terror"]],
["FNAF-4","FNAF 4",["terror"]],
["Funny-Shooter-2","Funny Shooter 2",["tiro"]],
["geometrydash","Geometry Dash",["plataforma","musica"]],
["getaway-shootout","Getaway Shootout",["tiro"]],
["gimme-the-aripod","Gimme the Airpod",["plataforma"]],
["goofy-ahh-dune","Goofy Ahh Dune",["estrategia"]],
["Google-snake","Google Snake",["plataforma"]],
["grind-craft","Grind Craft",["clicker"]],
["helicopter","Helicopter",["corrida"]],
["hextris","Hextris",["puzzle"]],
["idle-breakout","Idle Breakout",["clicker"]],
["idle-web-tycoon","Idle Web Tycoon",["clicker"]],
["impossiblequiz","Impossible Quiz",["puzzle"]],
["impossiblequiz-2","Impossible Quiz 2",["puzzle"]],
["jacksmith","Jacksmith",["simulacao"]],
["js-roulette","JS Roulette",["estrategia"]],
["learn-to-fly","Learn to Fly",["plataforma"]],
["learn-to-fly-2","Learn to Fly 2",["plataforma"]],
["learn-to-fly-3","Learn to Fly 3",["plataforma"]],
["learn-to-fly-idle","Learn to Fly Idle",["clicker"]],
["madalin-stunt-cars-2","Madalin Stunt Cars 2",["corrida"]],
["madalin-stunt-cars-3","Madalin Stunt Cars 3",["corrida"]],
["makesureitsclosed","Make Sure It's Closed",["plataforma"]],
["missiles","Missiles",["tiro"]],
["monkey-mart","Monkey Mart",["simulacao"]],
["moto-x3m","Moto X3M",["corrida"]],
["murder","Murder",["tiro"]],
["n-gon","N-Gon",["tiro"]],
["oh-flip","Oh Flip",["plataforma"]],
["other-tag","Other Tag",["acao"]],
["OVO","OVO",["plataforma"]],
["pandemic-2","Pandemic 2",["simulacao","estrategia"]],
["papa-louie","Papa Louie",["plataforma"]],
["papas-bakeria","Papa's Bakeria",["cozinha"]],
["papas-burgeria","Papa's Burgeria",["cozinha"]],
["papas-cheeseria","Papa's Cheeseria",["cozinha"]],
["papas-cupcakeria","Papa's Cupcakeria",["cozinha"]],
["papas-donuteria","Papa's Donuteria",["cozinha"]],
["papas-freezeria","Papa's Freezeria",["cozinha"]],
["papas-hotdoggeria","Papa's Hotdoggeria",["cozinha"]],
["papas-pancakeria","Papa's Pancakeria",["cozinha"]],
["papas-pastaria","Papa's Pastaria",["cozinha"]],
["papas-pizzeria","Papa's Pizzeria",["cozinha"]],
["papas-scooperia","Papa's Scooperia",["cozinha"]],
["papas-sushiria","Papa's Sushiria",["cozinha"]],
["papas-taco-mia","Papa's Taco Mia",["cozinha"]],
["papas-wingeria","Papa's Wingeria",["cozinha"]],
["papery-planes","Papery Planes",["plataforma"]],
["PC-breakdown","PC Breakdown",["simulacao"]],
["pcraft","PCraft",["simulacao"]],
["poly-track","Poly Track",["corrida"]],
["push-your-luck","Push Your Luck",["estrategia"]],
["ragdoll-archers","Ragdoll Archers",["tiro"]],
["ragdoll-hit","Ragdoll Hit",["acao"]],
["random-r6-op","Random R6 Op",["tiro"]],
["REAL-FS","Real Flight Simulator",["simulacao"]],
["retro-bowl","Retro Bowl",["esportes"]],
["retro-bowl-collage","Retro Bowl College",["esportes"]],
["Riddle-school-1","Riddle School 1",["puzzle"]],
["riddle-school-2","Riddle School 2",["puzzle"]],
["Riddle-School-3","Riddle School 3",["puzzle"]],
["Riddle-School-4","Riddle School 4",["puzzle"]],
["Riddle-School-5","Riddle School 5",["puzzle"]],
["rooftopsnipers","Rooftop Snipers",["tiro"]],
["run-2","Run 2",["infinito","plataforma"]],
["rusty-submarine","My Rusty Submarine",["corrida"]],
["sandtrix","Sandtrix",["puzzle"]],
["SD","Stickman Destruction",["acao"]],
["slope","Slope",["corrida","infinito"]],
["SM63","SM63",["reto","plataforma"]],
["SM64","SM64",["reto","plataforma"]],
["snake-io","Snake.io",["infinito","acao"]],
["snow-rider","Snow Rider",["corrida"]],
["soccer-random","Soccer Random",["esportes"]],
["sonic-cd","Sonic CD",["reto","plataforma"]],
["sort-the-court","Sort the Court",["estrategia","simulacao"]],
["space-company","Space Company",["clicker","estrategia"]],
["SRP","SRP",["acao"]],
["stickman-hook","Stickman Hook",["infinito","acao"]],
["subway-surfers-beijing","Subway Surfers Beijing",["corrida","infinito"]],
["subwaysurfers-sf","Subway Surfers SF",["corrida","infinito"]],
["superhot","Superhot",["tiro"]],
["tag","Tag",["acao"]],
["tanuki-sunset-halloween","Tanuki Sunset",["corrida"]],
["Terminus.JS","Terminus JS",["estrategia"]],
["territorial-io","Territorial.io",["estrategia","acao"]],
["tetris","Tetris",["puzzle"]],
["there-is-no-game","There is No Game",["puzzle"]],
["time-shooter-2","Time Shooter 2",["tiro"]],
["time-shooter-3","Time Shooter 3",["tiro"]],
["tiny-fishing","Tiny Fishing",["simulacao","clicker"]],
["tomb-of-the-mask","Tomb of the Mask",["plataforma"]],
["tunnel-rush-1","Tunnel Rush 1",["corrida"]],
["tunnel-rush-2","Tunnel Rush 2",["corrida"]],
["unicycle-hero","Unicycle Hero",["corrida"]],
["volley-random","Volley Random",["esportes"]],
["wheely-1","Wheely",["puzzle"]]
];
